### ISSUE TITLE
Unhandled Exception: PrismaInitializationException: Cannot find the query engine binary

### ISSUE THREAD

**Issue by YugalAnvation** [medz/prisma-dart#285]
I have followed all the steps to implement in flutter 
downgraded prisma and everything and when am trying to execute any query it is giving this error.
![Screenshot 2023-11-07 182011](https://github.com/medz/prisma-dart/assets/143159967/8bee38e7-9f9f-43f7-a707-b49610b4b425)

**Comment by medz** [comment]
Fixed in 3.4.5, copy new generated binary file.

**Comment by 0biWanKenobi** [comment]
Sorry but even if the binary is copied to the output dir, inside `prisma_client.dart` we still have the path to node_modules. And even if we change that path manually, the runtime error is still:

```
Cannot find the query engine binary (Basename: C:\path\does\not\matter\query-engine-windows.exe | prisma-query-engine)
```

**Comment by medz** [comment]
@0biWanKenobi This seems to be a problem with the upstream package `path`, which fails to correctly handle the basename in the path, causing the engine to be unable to obtain the basename and retrieve the engine files from the search directory.

Ideally, the error message should be: "Cannot find the query engine binary (Basename: query-engine-windows.exe | prisma-query-engine)"


<img width="690" alt="image" src="https://github.com/medz/prisma-dart/assets/5564821/a670beae-0a3f-4cf3-a15a-d4b16e67f617">

Everything appears with the full path "C:\path\does\not\matter\query-engine-windows.exe"

**Comment by medz** [comment]
https://github.com/medz/prisma-dart/discussions/314
